; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

build_flags = 
	-Iinclude
	-DMBEDTLS_SSL_IN_CONTENT_LEN=2048
	-DMBEDTLS_SSL_OUT_CONTENT_LEN=2048

lib_extra_dirs = 
	lib

lib_deps = 
	https://github.com/rfetick/MPU6050_light.git
	https://github.com/bblanchon/ArduinoJson.git
	madhephaestus/ESP32Servo@^3.0.6
	https://github.com/mikalhart/TinyGPSPlus.git
	https://github.com/bertmelis/espMqttClient.git

build_src_filter = 
	+<*>
	+<lib/globals/global_variables.cpp>
	+<lib/accelerometer/accelerometer.cpp>o par

board_build.partitions = partitions.csv
