#ifndef EVENTS_CONSTANTS_H
#define EVENTS_CONSTANTS_H

// Tipos de eventos
#define EVENT_BLOCK 1                // "BLOQUEIO"
#define EVENT_START_TIPPING 2        // "INICIO BASCULAMENTO"
#define EVENT_END_TIPPING 3          // "FIM BASCULAMENTO"
#define EVENT_SENSOR_CONNECTED 4     // "SENSOR CONECTADO AO APP"
#define EVENT_SENSOR_DISCONNECTED 5  // "SENSOR DESCONECTADO DO APP"
#define EVENT_SENSOR_CALIBRATED 6    // "SENSOR CALIBRADO"
#define EVENT_SENSOR_CLEARED 7       // "SENSOR LIMPO"
#define EVENT_BLOCK_VALUE_CHANGED 8  // "VALOR DE BLQ ALTERADO"

#endif  // EVENTS_CONSTANTS_H